config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "items#index"
  resources :users, only: [:index, :show]
  resources :items, except: :index do
    member do
      post 'pay'
    end
    collection do
      get 'search'
    end
    resources :comments, only: :create
  end
  resources :credit_cards, only: [:new, :create, :destroy] 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :item
  belongs_to :user 
  
  validates :text, presence: true
end

app/models/credit_card.rb
class CreditCard < ApplicationRecord
  belongs_to :user

  validates :customer_id,:card_id, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  # 空の場合保存させない
  with_options presence: true do
    validates :name,           null: false
    validates :detail,         null: false
    validates :image,          null: false
    validates :rental_start,   null: false
    validates :rental_end,     null: false
    validates :price,          null: false
    validates :postcode,       null: false
    validates :address_region, null: false
    validates :trading_status, null: false
  end

  # 字数制限
  validates :name, length: { maximum: 30 }
  validates :detail, length: { maximum: 1000 }

  mount_uploader :image, ImageUploader 

  belongs_to :user
  has_many :comments

  # 検索用メソッドの定義
  def self.search(search)
    return Item.all unless search
    Item.where('name LIKE(?)', "%#{search}%")
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true

  has_many  :items
  has_many  :comments
  has_one   :credit_card, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    comment =Comment.create(comment_params)
    if comment.save
      flash[:notice] = "コメントを送信しました。"
    else
      flash[:alert] = "コメントを送信できませんでした。"
    end
    redirect_to  controller: :items, action: :show, id: comment.item_id
  end

  private

  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, item_id: params[:item_id])
  end

end

app/controllers/credit_cards_controller.rb
class CreditCardsController < ApplicationController
  
  require "payjp"

  def new
    @card = CreditCard.find_by(user_id: current_user.id)
    if @card.present?
      redirect_to credit_card_path(current_user.id)
    else
      card = CreditCard.where(user_id: current_user.id)
    end
  end

  def create
    Payjp.api_key = Rails.application.credentials[:PAYJP_SECRET_KEY]
    if params['payjp-token'].blank?
      redirect_to action: :new
    else
      customer = Payjp::Customer.create(
        card: params['payjp-token'],
        metadata: {user_id: current_user.id},
        description: 'test'
      )
      @card = CreditCard.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        flash[:notice] = "支払い方法を登録しました"
        redirect_to root_path
      else
        flash[:alert] = "支払い方法を登録できませんでした。"
        redirect_to action: :new
      end
    end
  end

  def destroy
    creditCard = CreditCard.find(params[:id])
    if creditCard.destroy
      flash[:notice] = "支払い方法を削除しました。"
    else
      flash[:alert] = "支払い方法を削除できませんでした。"
    end
    redirect_to user_path(current_user.id)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action :move_to_index, except: [:index, :show]
  before_action :set_item, only: [:edit, :show]
  
  def index
    @items = Item.where.not(image: "").order(id: :desc).includes(:user)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      flash[:notice] = "商品を出品しました"
      redirect_to root_path
    else
      flash[:alert] = "商品を出品できませんでした"
      redirect_to new_item_path
    end 
  end

  def show
    @comment = Comment.new
    @comments = @item.comments.order(id: :desc).includes(:user)
  end

  def destroy
    item = Item.find(params[:id])
    if item.destroy
      flash[:notice] = "商品を削除しました"
      redirect_to root_path
    else
      flash[:alert] = "商品を削除できませんでした"
      redirect_to controller: 'items', action: 'show'
    end 
  end

  def edit
  end

  def update
    item = Item.find(params[:id])
    if item.update(item_params)
      flash[:notice] = "商品を更新しました"
    else
      flash[:alert] = "商品を更新できませんでした"
    end 
    redirect_to controller: 'items', action: 'show'
  end

  def pay
    @card = CreditCard.find_by(user_id: current_user.id)
    @item = Item.find(params[:id])
    Payjp.api_key = Rails.application.credentials[:PAYJP_SECRET_KEY]
    customer = Payjp::Customer.retrieve(@card.customer_id)
    if Payjp::Charge.create(amount: @item.price, customer: customer, currency: 'jpy' )
      @item.update!(trading_status: "貸し出し済")
      flash[:notice] = "商品をレンタルしました。"
      redirect_to new_item_path
    else
      render action: :buy
    end
  end

  def search
    @items = Item.search(params[:keyword]).where.not(image: "").order(id: :desc)
  end

  private

  def item_params
    params.require(:item).permit(:name, :detail, :image, :rental_start, :rental_end, :postcode, :address_region, :price, :trading_status).merge(user_id: current_user.id)
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end

  def set_item
    @item = Item.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/credit_cards/index.html.haml
= form_with  model: @credit_card, id: 'charge-form', class: 'card-form',local: true do |f|
  .form-wrap
    = f.label :price, "金額"
    = f.text_field :price, class:"price", placeholder:"例)2000", maxlength:"16"
  .form-wrap
    = f.label :number,  "カード番号"
    = f.text_field :number, class:"number", placeholder:"カード番号(半角英数字)", maxlength:"16"
  .form-wrap
    = f.label :cvc ,"ＣＶＣ"
    = f.text_field :cvc, class:"cvc", placeholder:"カード背面4桁もしくは3桁の番号", maxlength:"16"
  .form-wrap
    %p 有効期限
    .input-expiration-date-wrap
      = f.text_field :exp_month, class:"exp_month", placeholder:"例)3"
      %p 月
      = f.text_field :exp_year, class:"exp_year", placeholder:"例)24"
      %p 年
  = f.submit "購入" ,class:"button"

app/views/credit_cards/new.html.haml
.creditCardNewContents
  .creditCardNewContents__area
    .creditCardNewContents__area--title 支払い方法の登録
    .contents
      = form_with id: "charge-form", url: credit_cards_path, name: "inputForm", local: true do |f|
        .content
          .topic
            カード番号
            %span.labelDanger 必須
          = f.text_field :card_number, name: "number", class: "formDefault", placeholder: "半角数字のみ", maxlength: "16", type: "text", id: "card_number"

        .content
          .topic
            有効期限
            %span.labelDanger 必須
          .expirationDate__form
            = f.select :exp_month, [["01", 1],["02", 2],["03", 3],["04",4],["05",5],["06",6],["07",7],["08",8],["09",9],["10",10],["11",11],["12",12]],{prompt: "--"}, id: "exp_month", name: "exp_month", class: "formDefaultEx"
            .expirationDate__form--date 月
            = f.select :exp_year, [["2021", 2021],["2022", 2022],["2023",2023],["2024",2024],["2025",2025],["2026",2026],["2027",2027],["2028",2028],["2029",2029],["2030",2030]], {prompt: "--"}, id: "exp_year", name: "exp_year", class: "formDefaultEx"
            .expirationDate__form--date 年
        .content
          .topic
            セキュリティコード
            %span.labelDanger 必須
          = f.text_field :security_code, name: "cvc", class: "cvc", placeholder: "カード背面3~4桁の番号", maxlength: "4", id: "cvc", class: "formDefault"
        #card_token
          = f.submit id: "token_submit", value: "追加する", class: "submitBtn"

app/views/credit_cards/show.html.haml
%label 登録クレジットカード情報
%br
= "**** **** **** " + @default_card_information.last4
%br
- exp_month = @default_card_information.exp_month.to_s
- exp_year = @default_card_information.exp_year.to_s.slice(2,3)
= exp_month + " / " + exp_year
= form_tag(card_delete_path, method: :post, id: 'charge-form',  name: "inputForm") do
  %input{ type: "hidden", name: "card_id", value: "" }
  %button 削除する

app/views/items/_itemMain.html.haml
.itemMainContents
  = render partial: "items/searchForm"
  .itemMainContents__area
    .items
      - @items.each do |item|
        = link_to item_path(item.id), class: "item" do
          .item--image
            - if item.image?
              = image_tag item.image.url, size: "198x198"
            - else
              = image_tag "default.png", size: "198x198"
          .item--detail
            .item--detail__name
              = item.name
            .item--detail__info
              .price
                = item.price
                %span<>
                円 (税込)

app/views/items/_itemSubmit.html.haml
.itemSubmitContents
  = form_with(model: @item, local: true, class: "formArea", id: "itemNew") do |f|
    .content
      .topic
        商品名
        %span.labelDanger 必須
      = f.text_field :name, class: "formDefault", placeholder: "30字まで"

    .content
      .topic
        商品の詳細
        %span.labelDanger 必須
      = f.text_area :detail, class: "formDefault formDetail", placeholder: "商品の説明"

    .content.imageArea
      .postArea
        .topic
          画像
          %span.labelDanger 必須
        .formImage
          %label{for: "imageFile"}
            #imageBox
              = icon('fa','camera', class: "photo-icon")
              = f.file_field :image, id: "imageFile"
      .preview
        - if @item.persisted?
          .preview__image
            = image_tag @item.image.url
            .preview__image--remove 削除する

    .content
      .topic
        貸し出し期間期間
        %span.labelDanger 必須
      .rentalPeriod
        .rentalPeriod--start
          .rentalPeriod--start__title
            開始日
          = f.date_select :rental_start, use_month_numbers: true, with_css_classes:'formDefault'
        .rentalPeriod--end
          .rentalPeriod--end__title
            終了日
          = f.date_select :rental_end, use_month_numbers: true, with_css_classes:'formDefault'

    .content
      .topic
        貸し出し場所の郵便番号
        %span.labelDanger 必須
      = f.number_field :postcode, class: "formDefault", placeholder: '例）1234567'

    .content
      .topic
        貸し出し場所の住所
        %span.labelDanger 必須
      = f.text_field :address_region, class: "formDefault", placeholder: '例）滋賀県大津市におの浜１丁目'

    .content
      .topic
        金額
        %span.labelDanger 必須
      = f.number_field :price, class: "formDefault", placeholder: '0'

    .submit
      = f.submit class: "submitBtn", id: "itemSubmit", value: "送信"

app/views/items/_searchForm.html.haml
.searchForm
  = form_with(url: search_items_path, local: true, method: :get, class: "searchForm__area") do |f|
    = f.text_field :keyword, placeholder: "商品を検索する", class: "searchForm__area--input"
    = button_tag type: 'submit', class: "searchForm__area--btn" do
      = icon('fa', 'search')

app/views/items/edit.html.haml
= render partial: "itemSubmit", locals: { item: @item }

app/views/items/index.html.haml
= render partial: "items/itemMain"

app/views/items/new.html.haml
= render partial: "itemSubmit", locals: { item: @item }

app/views/items/search.html.haml
= render partial: "items/itemMain"

app/views/items/show.html.haml
.itemShowContents
  .item
    .item__image

      - if @item.image?
        = image_tag @item.image.url, size: "500x500"
      - else
        = image_tag "default.png", size: "500x500"

    .item__table
      %table.table
        %tbody
        %tr
          %th.table__left 出品者
          %td.table__right
            = @item.user.name
          %tr
            %th.table__left 商品名
            %td.table__right
              = @item.name
          %tr
            %th.table__left 価格
            %td.table__right
              = @item.price
              %span<>
              円 (税込)
          %tr
            %th.table__left 詳細
            %td.table__right
              = @item.detail
          %tr
            %th.table__left レンタル開始日
            %td.table__right
              = @item.rental_start
          %tr
            %th.table__left レンタル終了日
            %td.table__right
              = @item.rental_end
          %tr
            %th.table__left レンタル場所の郵便番号
            %td.table__right
              = @item.postcode
          %tr
            %th.table__left レンタル場所の住所
            %td.table__right
              = @item.address_region
          %tr
            %th.table__left 貸出し状況
            %td.table__right
              = @item.trading_status

    -if @item.trading_status == "出品中"
      - if user_signed_in? && current_user.id == @item.user_id
        .item--option
          = link_to "編集する", edit_item_path(@item.id), method: :get, class: "item--option__edit"
          = link_to "削除する", item_path(@item.id), method: :delete, class: "item--option__delete"

      - elsif user_signed_in? && current_user.credit_card.blank?
        .item--buy
          = link_to "支払方法の登録", new_credit_card_path, class: "item--buy__btn" 
      - elsif user_signed_in?
        .item--buy
          = link_to "購入する", pay_item_path(@item.id), method: :post, class: "item--buy__btn"

    .item--comment
      - if current_user
        = form_with(model: [@item, @comment], local: true) do |f|
          = f.text_area :text, class: "item--comment__body", rows: "2"
          %p.item--comment__notice 
            貸し出し期限の交渉などができます
          = f.submit class: "item--comment__submit", value: "コメントする"
      - else
        ※※※ コメントの投稿には新規登録/ログインが必要です ※※※
      .item--comment__area
        .topic ＜コメント一覧＞
        - if @comments
          - @comments.each do |comment|
            .comments
              .comments--contributor
                = comment.user.name
              .comments--content
                = comment.text
                .comments--content__time
                  = comment.created_at.strftime('%Y/%m/%d %H:%M:%S')

app/views/layouts/_footer.html.haml
.footer-content
  © 2020 Copyright

app/views/layouts/_header.html.haml
.header-content
  .header
    .header__left
      = link_to root_path, class: "application-name" do
        Shareitem
    .header__right
      .right
        - if user_signed_in?
          .right__lend-item
            = link_to "出品する", new_item_path, class: "right__lend-item--link"
          .right__user-config
            - if  current_user.credit_card.blank?
              = link_to "支払方法の登録", new_credit_card_path, class: "right__user-config--link"
            -else
              = link_to "支払方法の削除", credit_card_path(current_user.credit_card.id), method: :delete, class: "right__user-config--link"
          .right__logout
            = link_to "ログアウト", destroy_user_session_path, method: :delete, class: "right__logout--link"
        - else
          .right__login
            = link_to 'ログイン', new_user_session_path, class: "right__login--link"
          .right__signup
            = link_to '新規登録', new_user_registration_path, class: "right__signup--link"
              

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %title ShareItem
    %script{src: "https://js.pay.jp/", type: "text/javascript"}
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    = render partial: "layouts/header"
    .mainWrapper
      = render partial: 'layouts/notifications'
      = yield

    = render partial: "layouts/footer"

app/views/users/show.html.haml
.userShowContents
  .userShowContents__area
    .userShowContents__area--title ユーザー管理
    .contents
      .content
        - if  current_user.credit_card.blank?
          = link_to "支払い方法を登録する", new_credit_card_path, class: ""
        -else
          = link_to "支払い方法を削除する", credit_card_path(current_user.credit_card.id), method: :delete, class: ""